apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../series/c
- ../series/cx
- ../series/co

nameSuffix: .medium

patches:
- path: c.yaml
  target:
      name: "c1"
- path: c.yaml
  target:
      name: "co1"
- path: cx.yaml
  target:
      name: "cx1"
