# https://aws.amazon.com/ec2/instance-types/#Accelerated_Computing
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstanceType
metadata:
  name: "gn1"
  annotations:
    series.description: >-
      The GN Series provides instances types intended for VMs with NVIDIA GPU resources attached.
    series.class: "GPU"
spec:
  gpus:
  - resourceName: "nvidia.com/A400"
