apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachineInstanceType
metadata:
  annotations:
    series.class: Compute intensive
    series.description: The CX Series provides exclusive compute resources for compute
      intensive applications.
  name: cx1.large
spec:
  blockMultiQueue: true
  cpu:
    cores: 2
    dedicatedCpuPlacement: true
    ioThreadsPolicy: auto
    isolateEmulatorThread: true
    numa:
      guestMappingPassthrough: {}
  dedicatedIOThread: true
  memory:
    guest: 4Gi
  networkInterfaceMultiQueue: true
---
apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachineInstanceType
metadata:
  annotations:
    series.class: Compute intensive
    series.description: The CX Series provides exclusive compute resources for compute
      intensive applications.
  name: cx1.xlarge
spec:
  blockMultiQueue: true
  cpu:
    cores: 4
    dedicatedCpuPlacement: true
    ioThreadsPolicy: auto
    isolateEmulatorThread: true
    numa:
      guestMappingPassthrough: {}
  dedicatedIOThread: true
  memory:
    guest: 16Gi
  networkInterfaceMultiQueue: true
---
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstanceType
metadata:
  annotations:
    series.class: GPU
    series.description: The GN Series provides instances types intended for VMs with
      NVIDIA GPU resources attached.
  name: gn1.xlarge
spec:
  cpu:
    cores: 4
  gpus:
  - resourceName: nvidia.com/A400
  memory:
    guest: 16Gi
---
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstanceType
metadata:
  annotations:
    series.class: Memory intensive
    series.description: The M Series provides resources for memory intensive applications.
  name: m1.large
spec:
  cpu:
    cores: 2
  dedicatedCpuPlacement: true
  isolateEmulatorThread: true
  memory:
    guest: 16Gi
    hugepages:
      pageSize: 2Mi
---
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstanceType
metadata:
  annotations:
    series.class: Memory intensive
    series.description: The M Series provides resources for memory intensive applications.
  name: m1.xlarge
spec:
  cpu:
    cores: 4
  dedicatedCpuPlacement: true
  isolateEmulatorThread: true
  memory:
    guest: 32Gi
    hugepages:
      pageSize: 2Mi
---
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstanceType
metadata:
  annotations:
    series.class: General purpose
    series.description: The N Series is quite neutral and provides resources for general
      purpose applications.
  name: n1.large
spec:
  cpu:
    cores: 2
  memory:
    guest: 8Gi
---
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstanceType
metadata:
  annotations:
    series.class: General purpose
    series.description: The N Series is quite neutral and provides resources for general
      purpose applications.
  name: n1.small
spec:
  cpu:
    cores: 1
  memory:
    guest: 1Gi
---
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstanceType
metadata:
  annotations:
    series.class: General purpose
    series.description: The N Series is quite neutral and provides resources for general
      purpose applications.
  name: n1.xlarge
spec:
  cpu:
    cores: 4
  memory:
    guest: 8Gi
