apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachineInstanceType
metadata:
  annotations:
    series.class: Compute intensive
    series.description: |-
      The CX Series provides exclusive compute resources for compute intensive applications.
      The exclusive resources are given to the compute threads of the VM. In order to ensure this, some additional cores (depending on the number of disks and NICs) will be requested to offload the IO threading from cores dedicated to the workload. In addition, in this series, the NUMA topology of the used cores is provided to the VM.
    series.name: cx
  name: cx1.large
spec:
  blockMultiQueue: true
  cpu:
    cores: 2
    dedicatedCpuPlacement: true
    ioThreadsPolicy: auto
    isolateEmulatorThread: true
    numa:
      guestMappingPassthrough: {}
  dedicatedIOThread: true
  memory:
    guest: 4Gi
  networkInterfaceMultiQueue: true
---
apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachineInstanceType
metadata:
  annotations:
    series.class: Compute intensive
    series.description: |-
      The CX Series provides exclusive compute resources for compute intensive applications.
      The exclusive resources are given to the compute threads of the VM. In order to ensure this, some additional cores (depending on the number of disks and NICs) will be requested to offload the IO threading from cores dedicated to the workload. In addition, in this series, the NUMA topology of the used cores is provided to the VM.
    series.name: cx
  name: cx1.xlarge
spec:
  blockMultiQueue: true
  cpu:
    cores: 4
    dedicatedCpuPlacement: true
    ioThreadsPolicy: auto
    isolateEmulatorThread: true
    numa:
      guestMappingPassthrough: {}
  dedicatedIOThread: true
  memory:
    guest: 16Gi
  networkInterfaceMultiQueue: true
---
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstanceType
metadata:
  annotations:
    series.class: GPU
    series.description: The GN Series provides instances types intended for VMs with
      NVIDIA GPU resources attached.
    series.name: gn
  name: gn1.xlarge
spec:
  cpu:
    cores: 4
  gpus:
  - resourceName: nvidia.com/A400
  memory:
    guest: 16Gi
---
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstanceType
metadata:
  annotations:
    series.class: Memory intensive
    series.description: The M Series provides resources for memory intensive applications.
    series.name: m
  name: m1.large
spec:
  cpu:
    cores: 2
  dedicatedCpuPlacement: true
  isolateEmulatorThread: true
  memory:
    guest: 16Gi
    hugepages:
      pageSize: 2Mi
---
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstanceType
metadata:
  annotations:
    series.class: Memory intensive
    series.description: The M Series provides resources for memory intensive applications.
    series.name: m
  name: m1.xlarge
spec:
  cpu:
    cores: 4
  dedicatedCpuPlacement: true
  isolateEmulatorThread: true
  memory:
    guest: 32Gi
    hugepages:
      pageSize: 2Mi
---
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstanceType
metadata:
  annotations:
    series.class: General purpose
    series.description: |-
      The N Series is quite neutral and provides resources for general purpose applications.
      VMs of instance types will share physical CPU cores on a time-slice basis with other VMs.
    series.name: "n"
  name: n1.large
spec:
  cpu:
    cores: 2
  memory:
    guest: 8Gi
---
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstanceType
metadata:
  annotations:
    series.class: General purpose
    series.description: |-
      The N Series is quite neutral and provides resources for general purpose applications.
      VMs of instance types will share physical CPU cores on a time-slice basis with other VMs.
    series.name: "n"
  name: n1.small
spec:
  cpu:
    cores: 1
  memory:
    guest: 1Gi
---
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstanceType
metadata:
  annotations:
    series.class: General purpose
    series.description: |-
      The N Series is quite neutral and provides resources for general purpose applications.
      VMs of instance types will share physical CPU cores on a time-slice basis with other VMs.
    series.name: "n"
  name: n1.xlarge
spec:
  cpu:
    cores: 4
  memory:
    guest: 16Gi
