# https://aws.amazon.com/ec2/instance-types/#Accelerated_Computing
apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachineInstanceType
metadata:
  name: g
spec:
  cpu:
    cores: 1
  memory:
    guest: 1Gi
  gpus:
  - resourceName: "nvidia.com/A400"
