# https://aws.amazon.com/ec2/instance-types/#Compute_Optimized
apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachineInstanceType
metadata:
  name: c
spec:
  cpu:
    cores: 1
    ioThreadsPolicy: shared
    isolateEmulatorThread: True
    dedicatedCpuPlacement: True
    numa:
      guestMappingPassthrough: {}
  memory:
    guest: 1Gi
  networkInterfaceMultiQueue: true
  blockMultiQueue: true
  dedicatedIOThread: true
