# https://aws.amazon.com/ec2/instance-types/#Memory_Optimized
apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachineInstanceType
metadata:
  name: r
spec:
  memory:
    hugepages:
      pageSize: 2Mi
  dedicatedCpuPlacement: True
  isolateEmulatorThread: True

