# https://aws.amazon.com/ec2/instance-types/#Memory_Optimized
apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachineInstanceType
metadata:
  name: r
spec:
  cpu:
    cores: 1
  memory:
    guest: 1Gi
  dedicatedCpuPlacement: True
  isolateEmulatorThread: True

