apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../families/c
  - ../families/m
  - ../families/r
  - ../families/g

nameSuffix: .xlarge

patches:
  - path: c.yaml
    target:
      name: "c"
  - path: m.yaml
    target:
      name: "m"
  - path: r.yaml
    target:
      name: "r"
  - path: g.yaml
    target:
      name: "g"
